# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
jobs:
- job: DeployDev  

  variables:
    group: DevRunSettings

  steps:
  - checkout: none
  - script: "echo $(Key1)"

- job: DeployQA 

  variables:
    - group: QARunSettings

  steps:
  - script: echo $(Key1)