# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  branches:
    include:
    - master
    exclude:
    - releases/*

variables: 
  group: RunSettings

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Env value is: $(env)
    echo key value is: $(dev.Key)
    echo nested key value is: $($(env)Key)
  displayName: 'Run a multi-line script1'
