# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#trigger: none

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    pool: Hosted
    steps:
    - script: echo Hello, world! This is CI job
      displayName: 'Run a one-line script'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/s'
        Contents: '**'
        TarGetFoLDer: '$(System.defaultWorkingDirectory)/temp'
    - task: PublishPipelineArtifact@0
      displayName: Pipeline Artifact
      inputs:
        artifactName: Artifact1
        targetPath: '$(System.defaultWorkingDirectory)/temp/ashkirpack.nupkg'

    - upload: $(System.defaultWorkingDirectory)/temp/Jenkinsfile
      artifact: Artifact2

    - task: PublishBuildArtifacts@1
      displayName: Create FCS Artifact
      inputs:
        artifactName: Artifact3
        pathToPublish: $(System.defaultWorkingDirectory)/temp/PipelinesCD.yaml

    #  artifact: Extension
  - job: NoArtifactJob
    pool: Hosted
    dependsOn: Build
    steps:
      - powershell: ls $(Pipeline.Workspace) -r #Check the content of the workspace directory

  - job: DownloadAllArtifactJob
    pool: Hosted
    dependsOn: Build
    steps:
      - checkout: none
      - download: current
        artifact: Artifact3
      - powershell: |
          ls $(Pipeline.Workspace)/
          ls $(Pipeline.Workspace)/Artifact3

- stage: Deploy
  displayName: Deploy stage
  jobs:  
  - deployment: Deploy1
    displayName: Download All Artifacts
    pool: hosted
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  ls $(Pipeline.Workspace)/
                  ls $(Pipeline.Workspace)/Artifact1/
                  ls $(Pipeline.Workspace)/Artifact2/
                  ls $(Pipeline.Workspace)/Artifact3/
  - deployment: Deploy2
    displayName: partial download
    pool: hosted
    environment: Environment01
    strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                patterns: '**/*.nupkg'
                path: $(Pipeline.Workspace)/
              - powershell: |
                  ls $(Pipeline.Workspace)/

