# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: DevDeploy
  condition: eq(variables['env'],'Dev')
  variables: 
    group: DevRunSettings
  steps:
  - checkout: none
  - script: |
    echo Env value is: $(env)
    echo Key value is: $(Key1)
  displayName: 'Run a multi-line script1'

- job: DevDeploy
  condition: eq(variables['env'],'QA')
  variables: 
    group: QARunSettings
  steps:
  - checkout: none
  - script: |
    echo Env value is: $(env)
    echo Key value is: $(Key1)
  displayName: 'Run a multi-line script1'
