# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


jobs:
- job: DevDeploy
  variables: 
    group: DevRunSettings
  steps:
  - checkout: none
  - script: |
    echo Env value is $(env)
    echo Key value is $(Key1)

