# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
 pipelines:
   - pipeline: SmartHotel
     source: SmartHotel-CI
     trigger: true

stages:
  - stage: Deploy
    jobs:
    - job: test1
      pool: server
      steps:
        - script: 
        - checkout: self

    - deployment: WebDeployment
      pool: hosted
      environment: SmartHotelProd
      strategy:
       runOnce:
         deploy:
          steps:
            - download: current