

trigger: none

resources:
 pipelines:
   - pipeline: CIPipeline
     source: myAppCI
     trigger: 
      branches:
       include:
         - master
 packages:
   - package: somePackage
     type: Nuget
     connection: gh-rg
     name: nugetTest/OctocatApp
     trigger: true


stages:
- stage: Production
  displayName: Production 
  jobs: 
  - deployment: Deployment
    displayName: Deploy
    pool: 
      vmImage: 'ubuntu-latest'
    environment: ashkirEnv
    strategy:
      runOnce:
        deploy:
          steps: 
          # - getPackage: somePackage
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
