# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

jobs:
- job: DeployDev
  variables: 
    group: DevRunSettings
  steps:
  - checkout: none
  - script: echo value from script is $(Key1)

- job: DeployQA
  dependsOn: DeployDev
  variables: 
    group: QARunSettings
  steps:
  - checkout: none
  - script: echo value from script is $(Key1)


